inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/FrozenStringLiteralComment:
  Exclude:
    - gemfiles/*

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/StringLiterals:
  Exclude:
    - gemfiles/*
