require:
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/FrozenStringLiteralComment:
  Exclude:
    - gemfiles/*

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/StringLiterals:
  Exclude:
    - gemfiles/*

Style/FetchEnvVar:
  Enabled: false
