language: ruby
cache: bundler

rvm:
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
  - jruby-9.2
  - jruby-head

before_install:
  - gem install bundler

gemfile:
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/mongoid_4.0.gemfile
  - gemfiles/mongoid_5.0.gemfile
  - gemfiles/mongoid_6.0.gemfile
  - gemfiles/sequel_5.0.gemfile
  - gemfiles/mongo_mapper.gemfile

matrix:
  include:
    - rvm: ruby-head
      env: RUBYOPT="--enable-frozen-string-literal"
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head

addons:
  code_climate:
    repo_token: b84a33c35c698270ad54261655bc25161a0853386825a2d54fb1c7a11c2b2785
