name: Specs

on:
  merge_group:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
        ruby:
          - "3.2"
          - "3.3"
          - "3.4"
          - "4.0"
          - "head"
          - "jruby-10.0"
    runs-on: ${{ matrix.os }}-latest
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') || matrix.ruby == 'debug' }}
    steps:
    - uses: actions/checkout@v6
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    # Workaround while waiting for https://github.com/actions/runner-images/issues/13647
    # to be resolved
    - name: Fix gem directory permissions
      run: sudo chmod +t $(ruby -e 'puts Gem.default_dir')/gems

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install libsqlite3-dev
        bundle install --retry 3
    - name: Test with all appraisals
      if : ${{ matrix.ruby != 'head' }}
      run: bundle exec rake
    - name: Test without appraisals
      if : ${{ matrix.ruby == 'head' }}
      run: bundle exec rspec
